# Makefile.in generated by automake 1.9.6 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# === Miscellaneous ===



srcdir = .
top_srcdir = .

pkgdatadir = $(datadir)/dbus-python
pkglibdir = $(libdir)/dbus-python
pkgincludedir = $(includedir)/dbus-python
top_builddir = .
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = powerpc-unknown-linux-gnu
host_triplet = powerpc-unknown-linux-gnu
DIST_COMMON = README $(am__configure_deps) $(include_HEADERS) \
	$(nobase_python_PYTHON) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(srcdir)/dbus-python.pc.in $(top_srcdir)/configure \
	$(top_srcdir)/dbus/_version.py.in \
	$(top_srcdir)/test/TestSuitePythonService.service.in \
	$(top_srcdir)/test/tmp-session-bus.conf.in AUTHORS COPYING \
	ChangeLog INSTALL NEWS TODO autotools/compile \
	autotools/config.guess autotools/config.sub autotools/depcomp \
	autotools/install-sh autotools/ltmain.sh autotools/missing \
	autotools/py-compile
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/autotools/jhflags.m4 \
	$(top_srcdir)/autotools/python.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno configure.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES = dbus-python.pc dbus/_version.py \
	test/tmp-session-bus.conf test/TestSuitePythonService.service
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
am__installdirs = "$(DESTDIR)$(pyexecdir)" "$(DESTDIR)$(pythondir)" \
	"$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(includedir)"
pyexecLTLIBRARIES_INSTALL = $(INSTALL)
LTLIBRARIES = $(pyexec_LTLIBRARIES)
_dbus_bindings_la_LIBADD =
am__dbus_bindings_la_OBJECTS = _dbus_bindings_la-abstract.lo \
	_dbus_bindings_la-bus.lo _dbus_bindings_la-bytes.lo \
	_dbus_bindings_la-conn.lo _dbus_bindings_la-conn-methods.lo \
	_dbus_bindings_la-containers.lo _dbus_bindings_la-debug.lo \
	_dbus_bindings_la-exceptions.lo _dbus_bindings_la-float.lo \
	_dbus_bindings_la-generic.lo _dbus_bindings_la-int.lo \
	_dbus_bindings_la-mainloop.lo \
	_dbus_bindings_la-message-append.lo \
	_dbus_bindings_la-message.lo \
	_dbus_bindings_la-message-get-args.lo \
	_dbus_bindings_la-module.lo _dbus_bindings_la-pending-call.lo \
	_dbus_bindings_la-signature.lo _dbus_bindings_la-string.lo \
	_dbus_bindings_la-validation.lo
_dbus_bindings_la_OBJECTS = $(am__dbus_bindings_la_OBJECTS)
_dbus_glib_bindings_la_LIBADD =
am__dbus_glib_bindings_la_OBJECTS = _dbus_glib_bindings_la-module.lo
_dbus_glib_bindings_la_OBJECTS = $(am__dbus_glib_bindings_la_OBJECTS)
DEFAULT_INCLUDES = -I. -I$(srcdir) -I.
depcomp = $(SHELL) $(top_srcdir)/autotools/depcomp
am__depfiles_maybe = depfiles
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(_dbus_bindings_la_SOURCES) \
	$(_dbus_glib_bindings_la_SOURCES)
DIST_SOURCES = $(_dbus_bindings_la_SOURCES) \
	$(_dbus_glib_bindings_la_SOURCES)
nobase_pythonPYTHON_INSTALL = $(install_sh_DATA)
py_compile = $(top_srcdir)/autotools/py-compile
pkgconfigDATA_INSTALL = $(INSTALL_DATA)
DATA = $(pkgconfig_DATA)
includeHEADERS_INSTALL = $(INSTALL_HEADER)
HEADERS = $(include_HEADERS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/smcv/Collabora/branches/dbus/dbus-python/autotools/missing --run aclocal-1.9 
ACLOCAL_AMFLAGS = -I autotools -I .
AMDEP_FALSE = #
AMDEP_TRUE = 
AMTAR = ${SHELL} /home/smcv/Collabora/branches/dbus/dbus-python/autotools/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /home/smcv/Collabora/branches/dbus/dbus-python/autotools/missing --run autoconf
AUTOHEADER = ${SHELL} /home/smcv/Collabora/branches/dbus/dbus-python/autotools/missing --run autoheader
AUTOMAKE = ${SHELL} /home/smcv/Collabora/branches/dbus/dbus-python/autotools/missing --run automake-1.9
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2 -Wall -Wextra -Wno-missing-field-initializers -Wdeclaration-after-statement -std=c9x -fno-strict-aliasing
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DBUS_CFLAGS = -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  
DBUS_GLIB_CFLAGS = -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  
DBUS_GLIB_LIBS = -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0  
DBUS_LIBS = -ldbus-glib-1 -ldbus-1 -lgobject-2.0 -lglib-2.0  
DBUS_PYTHON_MAJOR_VERSION = 0
DBUS_PYTHON_MICRO_VERSION = 93
DBUS_PYTHON_MINOR_VERSION = 79
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO = echo
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
ENABLE_API_DOCS_FALSE = 
ENABLE_API_DOCS_TRUE = #
EPYDOC = 
EXEEXT = 
GREP = /bin/grep
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/smcv/Collabora/branches/dbus/dbus-python/autotools/missing --run makeinfo
OBJEXT = o
PACKAGE = dbus-python
PACKAGE_BUGREPORT = http://bugzilla.gnome.org/enter_bug.cgi?product=dbus&component=python
PACKAGE_NAME = dbus-python
PACKAGE_STRING = dbus-python 0.79.93
PACKAGE_TARNAME = dbus-python
PACKAGE_VERSION = 0.79.93
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PLATFORM = linux-ppc
PYTHON = /usr/bin/python
PYTHON_EXEC_PREFIX = ${exec_prefix}
PYTHON_INCLUDES = -I/usr/include/python2.4
PYTHON_PLATFORM = linux2
PYTHON_PREFIX = ${prefix}
PYTHON_VERSION = 2.4
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 0.79.93
ac_ct_CC = gcc
am__fastdepCC_FALSE = #
am__fastdepCC_TRUE = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = powerpc-unknown-linux-gnu
build_alias = 
build_cpu = powerpc
build_os = linux-gnu
build_vendor = unknown
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = powerpc-unknown-linux-gnu
host_alias = 
host_cpu = powerpc
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = /home/smcv/Collabora/branches/dbus/dbus-python/autotools/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = mkdir -p --
oldincludedir = /usr/include
pdfdir = ${docdir}
pkgpyexecdir = ${pyexecdir}/dbus-python
pkgpythondir = ${pythondir}/dbus-python
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
pyexecdir = ${exec_prefix}/lib/python2.4/site-packages
pythondir = ${prefix}/lib/python2.4/site-packages
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target_alias = 
CLEANFILES = 
EXTRA_DIST = API_CHANGES.txt dbus-python.pc.in HACKING.txt \
	     AUTHORS COPYING ChangeLog NEWS TODO \
	     examples/example-client.py \
	     examples/example-service.py \
	     examples/example-signal-emitter.py \
	     examples/example-signal-recipient.py \
	     examples/list-system-services.py \
	     test/cross-test-client.py \
	     test/cross-test-server.py \
	     test/crosstest.py \
	     test/run-test.sh \
	     test/run-with-tmp-session-bus.sh \
	     test/test-client.py \
	     test/test-service.py \
	     test/test-signals.py \
	     test/test-standalone.py \
	     test/TestSuitePythonService.service.in \
	     test/tmp-session-bus.conf.in

# miss out the gconf examples for now - they don't work
pkgconfigdir = $(libdir)/pkgconfig
pkgconfig_DATA = dbus-python.pc
include_HEADERS = include/dbus-python.h

# === Pure Python ===
nobase_python_PYTHON = dbus_bindings.py \
		       dbus/dbus_bindings.py \
		       dbus/_dbus.py \
		       dbus/decorators.py \
		       dbus/exceptions.py \
		       dbus/glib.py \
		       dbus/__init__.py \
		       dbus/introspect_parser.py \
		       dbus/lowlevel.py \
		       dbus/mainloop/__init__.py \
		       dbus/mainloop/glib.py \
		       dbus/proxies.py \
		       dbus/service.py \
		       dbus/types.py


# === Python C extensions ===
pyexec_LTLIBRARIES = _dbus_bindings.la _dbus_glib_bindings.la
_dbus_bindings_la_CPPFLAGS = -I$(srcdir)/include \
			     $(DBUS_CFLAGS) \
			     $(PYTHON_INCLUDES)

_dbus_bindings_la_LDFLAGS = -module -avoid-version \
			 -export-symbols-regex init_dbus_bindings \
			 $(DBUS_LIBS)

_dbus_bindings_la_SOURCES = \
			    _dbus_bindings/abstract.c \
			    _dbus_bindings/bus.c \
			    _dbus_bindings/bytes.c \
			    _dbus_bindings/conn.c \
			    _dbus_bindings/conn-internal.h \
			    _dbus_bindings/conn-methods.c \
			    _dbus_bindings/containers.c \
			    _dbus_bindings/dbus_bindings-internal.h \
			    _dbus_bindings/debug.c \
			    _dbus_bindings/exceptions.c \
			    _dbus_bindings/float.c \
			    _dbus_bindings/generic.c \
			    _dbus_bindings/int.c \
			    _dbus_bindings/mainloop.c \
			    _dbus_bindings/message-append.c \
			    _dbus_bindings/message.c \
			    _dbus_bindings/message-get-args.c \
			    _dbus_bindings/message-internal.h \
			    _dbus_bindings/module.c \
			    _dbus_bindings/pending-call.c \
			    _dbus_bindings/signature.c \
			    _dbus_bindings/string.c \
			    _dbus_bindings/types-internal.h \
			    _dbus_bindings/validation.c \
			    include/dbus-python.h

_dbus_glib_bindings_la_CPPFLAGS = -I$(top_srcdir)/include \
				  $(DBUS_CFLAGS) \
				  $(DBUS_GLIB_CFLAGS) \
				  $(PYTHON_INCLUDES)

_dbus_glib_bindings_la_LDFLAGS = -module -avoid-version \
			 -export-symbols-regex init_dbus_glib_bindings \
			 $(DBUS_LIBS) $(DBUS_GLIB_LIBS)

_dbus_glib_bindings_la_SOURCES = _dbus_glib_bindings/module.c \
				 include/dbus-python.h


# === Tests ===
PWD = `pwd`
TESTS_ENVIRONMENT = DBUS_TOP_SRCDIR="$(PWD)/$(top_srcdir)" \
		    DBUS_TOP_BUILDDIR="$(PWD)" \
		    DBUS_PYTHON_VERSION='$(PACKAGE_VERSION)' \
		    PYTHONPATH="$(PWD)/.libs:$(PWD)/$(top_srcdir):$(PWD)/$(top_srcdir)/test" \
		    PYTHON='$(PYTHON)'

TESTS = test/run-test.sh
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu '; \
	      cd $(srcdir) && $(AUTOMAKE) --gnu  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	cd $(top_srcdir) && $(AUTOHEADER)
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
dbus-python.pc: $(top_builddir)/config.status $(srcdir)/dbus-python.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dbus/_version.py: $(top_builddir)/config.status $(top_srcdir)/dbus/_version.py.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
test/tmp-session-bus.conf: $(top_builddir)/config.status $(top_srcdir)/test/tmp-session-bus.conf.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
test/TestSuitePythonService.service: $(top_builddir)/config.status $(top_srcdir)/test/TestSuitePythonService.service.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-pyexecLTLIBRARIES: $(pyexec_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(pyexecdir)" || $(mkdir_p) "$(DESTDIR)$(pyexecdir)"
	@list='$(pyexec_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    f=$(am__strip_dir) \
	    echo " $(LIBTOOL) --mode=install $(pyexecLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) '$$p' '$(DESTDIR)$(pyexecdir)/$$f'"; \
	    $(LIBTOOL) --mode=install $(pyexecLTLIBRARIES_INSTALL) $(INSTALL_STRIP_FLAG) "$$p" "$(DESTDIR)$(pyexecdir)/$$f"; \
	  else :; fi; \
	done

uninstall-pyexecLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@set -x; list='$(pyexec_LTLIBRARIES)'; for p in $$list; do \
	  p=$(am__strip_dir) \
	  echo " $(LIBTOOL) --mode=uninstall rm -f '$(DESTDIR)$(pyexecdir)/$$p'"; \
	  $(LIBTOOL) --mode=uninstall rm -f "$(DESTDIR)$(pyexecdir)/$$p"; \
	done

clean-pyexecLTLIBRARIES:
	-test -z "$(pyexec_LTLIBRARIES)" || rm -f $(pyexec_LTLIBRARIES)
	@list='$(pyexec_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
_dbus_bindings.la: $(_dbus_bindings_la_OBJECTS) $(_dbus_bindings_la_DEPENDENCIES) 
	$(LINK) -rpath $(pyexecdir) $(_dbus_bindings_la_LDFLAGS) $(_dbus_bindings_la_OBJECTS) $(_dbus_bindings_la_LIBADD) $(LIBS)
_dbus_glib_bindings.la: $(_dbus_glib_bindings_la_OBJECTS) $(_dbus_glib_bindings_la_DEPENDENCIES) 
	$(LINK) -rpath $(pyexecdir) $(_dbus_glib_bindings_la_LDFLAGS) $(_dbus_glib_bindings_la_OBJECTS) $(_dbus_glib_bindings_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/_dbus_bindings_la-abstract.Plo
include ./$(DEPDIR)/_dbus_bindings_la-bus.Plo
include ./$(DEPDIR)/_dbus_bindings_la-bytes.Plo
include ./$(DEPDIR)/_dbus_bindings_la-conn-methods.Plo
include ./$(DEPDIR)/_dbus_bindings_la-conn.Plo
include ./$(DEPDIR)/_dbus_bindings_la-containers.Plo
include ./$(DEPDIR)/_dbus_bindings_la-debug.Plo
include ./$(DEPDIR)/_dbus_bindings_la-exceptions.Plo
include ./$(DEPDIR)/_dbus_bindings_la-float.Plo
include ./$(DEPDIR)/_dbus_bindings_la-generic.Plo
include ./$(DEPDIR)/_dbus_bindings_la-int.Plo
include ./$(DEPDIR)/_dbus_bindings_la-mainloop.Plo
include ./$(DEPDIR)/_dbus_bindings_la-message-append.Plo
include ./$(DEPDIR)/_dbus_bindings_la-message-get-args.Plo
include ./$(DEPDIR)/_dbus_bindings_la-message.Plo
include ./$(DEPDIR)/_dbus_bindings_la-module.Plo
include ./$(DEPDIR)/_dbus_bindings_la-pending-call.Plo
include ./$(DEPDIR)/_dbus_bindings_la-signature.Plo
include ./$(DEPDIR)/_dbus_bindings_la-string.Plo
include ./$(DEPDIR)/_dbus_bindings_la-validation.Plo
include ./$(DEPDIR)/_dbus_glib_bindings_la-module.Plo

.c.o:
	if $(COMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ $<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	if $(COMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ `$(CYGPATH_W) '$<'`; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	if $(LTCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ $<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Plo"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

_dbus_bindings_la-abstract.lo: _dbus_bindings/abstract.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-abstract.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-abstract.Tpo" -c -o _dbus_bindings_la-abstract.lo `test -f '_dbus_bindings/abstract.c' || echo '$(srcdir)/'`_dbus_bindings/abstract.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-abstract.Tpo" "$(DEPDIR)/_dbus_bindings_la-abstract.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-abstract.Tpo"; exit 1; fi
#	source='_dbus_bindings/abstract.c' object='_dbus_bindings_la-abstract.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-abstract.lo `test -f '_dbus_bindings/abstract.c' || echo '$(srcdir)/'`_dbus_bindings/abstract.c

_dbus_bindings_la-bus.lo: _dbus_bindings/bus.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-bus.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-bus.Tpo" -c -o _dbus_bindings_la-bus.lo `test -f '_dbus_bindings/bus.c' || echo '$(srcdir)/'`_dbus_bindings/bus.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-bus.Tpo" "$(DEPDIR)/_dbus_bindings_la-bus.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-bus.Tpo"; exit 1; fi
#	source='_dbus_bindings/bus.c' object='_dbus_bindings_la-bus.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-bus.lo `test -f '_dbus_bindings/bus.c' || echo '$(srcdir)/'`_dbus_bindings/bus.c

_dbus_bindings_la-bytes.lo: _dbus_bindings/bytes.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-bytes.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-bytes.Tpo" -c -o _dbus_bindings_la-bytes.lo `test -f '_dbus_bindings/bytes.c' || echo '$(srcdir)/'`_dbus_bindings/bytes.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-bytes.Tpo" "$(DEPDIR)/_dbus_bindings_la-bytes.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-bytes.Tpo"; exit 1; fi
#	source='_dbus_bindings/bytes.c' object='_dbus_bindings_la-bytes.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-bytes.lo `test -f '_dbus_bindings/bytes.c' || echo '$(srcdir)/'`_dbus_bindings/bytes.c

_dbus_bindings_la-conn.lo: _dbus_bindings/conn.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-conn.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-conn.Tpo" -c -o _dbus_bindings_la-conn.lo `test -f '_dbus_bindings/conn.c' || echo '$(srcdir)/'`_dbus_bindings/conn.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-conn.Tpo" "$(DEPDIR)/_dbus_bindings_la-conn.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-conn.Tpo"; exit 1; fi
#	source='_dbus_bindings/conn.c' object='_dbus_bindings_la-conn.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-conn.lo `test -f '_dbus_bindings/conn.c' || echo '$(srcdir)/'`_dbus_bindings/conn.c

_dbus_bindings_la-conn-methods.lo: _dbus_bindings/conn-methods.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-conn-methods.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-conn-methods.Tpo" -c -o _dbus_bindings_la-conn-methods.lo `test -f '_dbus_bindings/conn-methods.c' || echo '$(srcdir)/'`_dbus_bindings/conn-methods.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-conn-methods.Tpo" "$(DEPDIR)/_dbus_bindings_la-conn-methods.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-conn-methods.Tpo"; exit 1; fi
#	source='_dbus_bindings/conn-methods.c' object='_dbus_bindings_la-conn-methods.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-conn-methods.lo `test -f '_dbus_bindings/conn-methods.c' || echo '$(srcdir)/'`_dbus_bindings/conn-methods.c

_dbus_bindings_la-containers.lo: _dbus_bindings/containers.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-containers.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-containers.Tpo" -c -o _dbus_bindings_la-containers.lo `test -f '_dbus_bindings/containers.c' || echo '$(srcdir)/'`_dbus_bindings/containers.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-containers.Tpo" "$(DEPDIR)/_dbus_bindings_la-containers.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-containers.Tpo"; exit 1; fi
#	source='_dbus_bindings/containers.c' object='_dbus_bindings_la-containers.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-containers.lo `test -f '_dbus_bindings/containers.c' || echo '$(srcdir)/'`_dbus_bindings/containers.c

_dbus_bindings_la-debug.lo: _dbus_bindings/debug.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-debug.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-debug.Tpo" -c -o _dbus_bindings_la-debug.lo `test -f '_dbus_bindings/debug.c' || echo '$(srcdir)/'`_dbus_bindings/debug.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-debug.Tpo" "$(DEPDIR)/_dbus_bindings_la-debug.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-debug.Tpo"; exit 1; fi
#	source='_dbus_bindings/debug.c' object='_dbus_bindings_la-debug.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-debug.lo `test -f '_dbus_bindings/debug.c' || echo '$(srcdir)/'`_dbus_bindings/debug.c

_dbus_bindings_la-exceptions.lo: _dbus_bindings/exceptions.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-exceptions.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-exceptions.Tpo" -c -o _dbus_bindings_la-exceptions.lo `test -f '_dbus_bindings/exceptions.c' || echo '$(srcdir)/'`_dbus_bindings/exceptions.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-exceptions.Tpo" "$(DEPDIR)/_dbus_bindings_la-exceptions.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-exceptions.Tpo"; exit 1; fi
#	source='_dbus_bindings/exceptions.c' object='_dbus_bindings_la-exceptions.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-exceptions.lo `test -f '_dbus_bindings/exceptions.c' || echo '$(srcdir)/'`_dbus_bindings/exceptions.c

_dbus_bindings_la-float.lo: _dbus_bindings/float.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-float.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-float.Tpo" -c -o _dbus_bindings_la-float.lo `test -f '_dbus_bindings/float.c' || echo '$(srcdir)/'`_dbus_bindings/float.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-float.Tpo" "$(DEPDIR)/_dbus_bindings_la-float.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-float.Tpo"; exit 1; fi
#	source='_dbus_bindings/float.c' object='_dbus_bindings_la-float.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-float.lo `test -f '_dbus_bindings/float.c' || echo '$(srcdir)/'`_dbus_bindings/float.c

_dbus_bindings_la-generic.lo: _dbus_bindings/generic.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-generic.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-generic.Tpo" -c -o _dbus_bindings_la-generic.lo `test -f '_dbus_bindings/generic.c' || echo '$(srcdir)/'`_dbus_bindings/generic.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-generic.Tpo" "$(DEPDIR)/_dbus_bindings_la-generic.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-generic.Tpo"; exit 1; fi
#	source='_dbus_bindings/generic.c' object='_dbus_bindings_la-generic.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-generic.lo `test -f '_dbus_bindings/generic.c' || echo '$(srcdir)/'`_dbus_bindings/generic.c

_dbus_bindings_la-int.lo: _dbus_bindings/int.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-int.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-int.Tpo" -c -o _dbus_bindings_la-int.lo `test -f '_dbus_bindings/int.c' || echo '$(srcdir)/'`_dbus_bindings/int.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-int.Tpo" "$(DEPDIR)/_dbus_bindings_la-int.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-int.Tpo"; exit 1; fi
#	source='_dbus_bindings/int.c' object='_dbus_bindings_la-int.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-int.lo `test -f '_dbus_bindings/int.c' || echo '$(srcdir)/'`_dbus_bindings/int.c

_dbus_bindings_la-mainloop.lo: _dbus_bindings/mainloop.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-mainloop.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-mainloop.Tpo" -c -o _dbus_bindings_la-mainloop.lo `test -f '_dbus_bindings/mainloop.c' || echo '$(srcdir)/'`_dbus_bindings/mainloop.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-mainloop.Tpo" "$(DEPDIR)/_dbus_bindings_la-mainloop.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-mainloop.Tpo"; exit 1; fi
#	source='_dbus_bindings/mainloop.c' object='_dbus_bindings_la-mainloop.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-mainloop.lo `test -f '_dbus_bindings/mainloop.c' || echo '$(srcdir)/'`_dbus_bindings/mainloop.c

_dbus_bindings_la-message-append.lo: _dbus_bindings/message-append.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-message-append.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-message-append.Tpo" -c -o _dbus_bindings_la-message-append.lo `test -f '_dbus_bindings/message-append.c' || echo '$(srcdir)/'`_dbus_bindings/message-append.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-message-append.Tpo" "$(DEPDIR)/_dbus_bindings_la-message-append.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-message-append.Tpo"; exit 1; fi
#	source='_dbus_bindings/message-append.c' object='_dbus_bindings_la-message-append.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-message-append.lo `test -f '_dbus_bindings/message-append.c' || echo '$(srcdir)/'`_dbus_bindings/message-append.c

_dbus_bindings_la-message.lo: _dbus_bindings/message.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-message.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-message.Tpo" -c -o _dbus_bindings_la-message.lo `test -f '_dbus_bindings/message.c' || echo '$(srcdir)/'`_dbus_bindings/message.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-message.Tpo" "$(DEPDIR)/_dbus_bindings_la-message.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-message.Tpo"; exit 1; fi
#	source='_dbus_bindings/message.c' object='_dbus_bindings_la-message.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-message.lo `test -f '_dbus_bindings/message.c' || echo '$(srcdir)/'`_dbus_bindings/message.c

_dbus_bindings_la-message-get-args.lo: _dbus_bindings/message-get-args.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-message-get-args.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-message-get-args.Tpo" -c -o _dbus_bindings_la-message-get-args.lo `test -f '_dbus_bindings/message-get-args.c' || echo '$(srcdir)/'`_dbus_bindings/message-get-args.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-message-get-args.Tpo" "$(DEPDIR)/_dbus_bindings_la-message-get-args.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-message-get-args.Tpo"; exit 1; fi
#	source='_dbus_bindings/message-get-args.c' object='_dbus_bindings_la-message-get-args.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-message-get-args.lo `test -f '_dbus_bindings/message-get-args.c' || echo '$(srcdir)/'`_dbus_bindings/message-get-args.c

_dbus_bindings_la-module.lo: _dbus_bindings/module.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-module.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-module.Tpo" -c -o _dbus_bindings_la-module.lo `test -f '_dbus_bindings/module.c' || echo '$(srcdir)/'`_dbus_bindings/module.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-module.Tpo" "$(DEPDIR)/_dbus_bindings_la-module.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-module.Tpo"; exit 1; fi
#	source='_dbus_bindings/module.c' object='_dbus_bindings_la-module.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-module.lo `test -f '_dbus_bindings/module.c' || echo '$(srcdir)/'`_dbus_bindings/module.c

_dbus_bindings_la-pending-call.lo: _dbus_bindings/pending-call.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-pending-call.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-pending-call.Tpo" -c -o _dbus_bindings_la-pending-call.lo `test -f '_dbus_bindings/pending-call.c' || echo '$(srcdir)/'`_dbus_bindings/pending-call.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-pending-call.Tpo" "$(DEPDIR)/_dbus_bindings_la-pending-call.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-pending-call.Tpo"; exit 1; fi
#	source='_dbus_bindings/pending-call.c' object='_dbus_bindings_la-pending-call.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-pending-call.lo `test -f '_dbus_bindings/pending-call.c' || echo '$(srcdir)/'`_dbus_bindings/pending-call.c

_dbus_bindings_la-signature.lo: _dbus_bindings/signature.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-signature.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-signature.Tpo" -c -o _dbus_bindings_la-signature.lo `test -f '_dbus_bindings/signature.c' || echo '$(srcdir)/'`_dbus_bindings/signature.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-signature.Tpo" "$(DEPDIR)/_dbus_bindings_la-signature.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-signature.Tpo"; exit 1; fi
#	source='_dbus_bindings/signature.c' object='_dbus_bindings_la-signature.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-signature.lo `test -f '_dbus_bindings/signature.c' || echo '$(srcdir)/'`_dbus_bindings/signature.c

_dbus_bindings_la-string.lo: _dbus_bindings/string.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-string.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-string.Tpo" -c -o _dbus_bindings_la-string.lo `test -f '_dbus_bindings/string.c' || echo '$(srcdir)/'`_dbus_bindings/string.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-string.Tpo" "$(DEPDIR)/_dbus_bindings_la-string.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-string.Tpo"; exit 1; fi
#	source='_dbus_bindings/string.c' object='_dbus_bindings_la-string.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-string.lo `test -f '_dbus_bindings/string.c' || echo '$(srcdir)/'`_dbus_bindings/string.c

_dbus_bindings_la-validation.lo: _dbus_bindings/validation.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_bindings_la-validation.lo -MD -MP -MF "$(DEPDIR)/_dbus_bindings_la-validation.Tpo" -c -o _dbus_bindings_la-validation.lo `test -f '_dbus_bindings/validation.c' || echo '$(srcdir)/'`_dbus_bindings/validation.c; \
	then mv -f "$(DEPDIR)/_dbus_bindings_la-validation.Tpo" "$(DEPDIR)/_dbus_bindings_la-validation.Plo"; else rm -f "$(DEPDIR)/_dbus_bindings_la-validation.Tpo"; exit 1; fi
#	source='_dbus_bindings/validation.c' object='_dbus_bindings_la-validation.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_bindings_la-validation.lo `test -f '_dbus_bindings/validation.c' || echo '$(srcdir)/'`_dbus_bindings/validation.c

_dbus_glib_bindings_la-module.lo: _dbus_glib_bindings/module.c
	if $(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_glib_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT _dbus_glib_bindings_la-module.lo -MD -MP -MF "$(DEPDIR)/_dbus_glib_bindings_la-module.Tpo" -c -o _dbus_glib_bindings_la-module.lo `test -f '_dbus_glib_bindings/module.c' || echo '$(srcdir)/'`_dbus_glib_bindings/module.c; \
	then mv -f "$(DEPDIR)/_dbus_glib_bindings_la-module.Tpo" "$(DEPDIR)/_dbus_glib_bindings_la-module.Plo"; else rm -f "$(DEPDIR)/_dbus_glib_bindings_la-module.Tpo"; exit 1; fi
#	source='_dbus_glib_bindings/module.c' object='_dbus_glib_bindings_la-module.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LIBTOOL) --tag=CC --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(_dbus_glib_bindings_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o _dbus_glib_bindings_la-module.lo `test -f '_dbus_glib_bindings/module.c' || echo '$(srcdir)/'`_dbus_glib_bindings/module.c

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool
uninstall-info-am:
install-nobase_pythonPYTHON: $(nobase_python_PYTHON)
	@$(NORMAL_INSTALL)
	test -z "$(pythondir)" || $(mkdir_p) "$(DESTDIR)$(pythondir)"
	@$(am__vpath_adj_setup) \
	list='$(nobase_python_PYTHON)'; dlist=''; for p in $$list; do\
	  if test -f "$$p"; then b=; else b="$(srcdir)/"; fi; \
	  if test -f $$b$$p; then \
	    $(am__vpath_adj) \
	    dlist="$$dlist $$f"; \
	    echo " $(nobase_pythonPYTHON_INSTALL) '$$b$$p' '$(DESTDIR)$(pythondir)/$$f'"; \
	    $(nobase_pythonPYTHON_INSTALL) "$$b$$p" "$(DESTDIR)$(pythondir)/$$f"; \
	  else :; fi; \
	done; \
	if test -n "$$dlist"; then \
	  if test -z "$(DESTDIR)"; then \
	    PYTHON=$(PYTHON) $(py_compile) --basedir "$(pythondir)" $$dlist; \
	  else \
	    PYTHON=$(PYTHON) $(py_compile) --destdir "$(DESTDIR)" --basedir "$(pythondir)" $$dlist; \
	  fi; \
	else :; fi

uninstall-nobase_pythonPYTHON:
	@$(NORMAL_UNINSTALL)
	@$(am__vpath_adj_setup) \
	list='$(nobase_python_PYTHON)'; dlist=''; for p in $$list; do\
	  $(am__vpath_adj) \
	  rm -f "$(DESTDIR)$(pythondir)/$$f"; \
	  rm -f "$(DESTDIR)$(pythondir)/$${f}c"; \
	  rm -f "$(DESTDIR)$(pythondir)/$${f}o"; \
	done
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(pkgconfigdir)" || $(mkdir_p) "$(DESTDIR)$(pkgconfigdir)"
	@list='$(pkgconfig_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(pkgconfigDATA_INSTALL) '$$d$$p' '$(DESTDIR)$(pkgconfigdir)/$$f'"; \
	  $(pkgconfigDATA_INSTALL) "$$d$$p" "$(DESTDIR)$(pkgconfigdir)/$$f"; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(pkgconfigdir)/$$f'"; \
	  rm -f "$(DESTDIR)$(pkgconfigdir)/$$f"; \
	done
install-includeHEADERS: $(include_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(includedir)" || $(mkdir_p) "$(DESTDIR)$(includedir)"
	@list='$(include_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(includeHEADERS_INSTALL) '$$d$$p' '$(DESTDIR)$(includedir)/$$f'"; \
	  $(includeHEADERS_INSTALL) "$$d$$p" "$(DESTDIR)$(includedir)/$$f"; \
	done

uninstall-includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(include_HEADERS)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(includedir)/$$f'"; \
	  rm -f "$(DESTDIR)$(includedir)/$$f"; \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

check-TESTS: $(TESTS)
	@failed=0; all=0; xfail=0; xpass=0; skip=0; \
	srcdir=$(srcdir); export srcdir; \
	list='$(TESTS)'; \
	if test -n "$$list"; then \
	  for tst in $$list; do \
	    if test -f ./$$tst; then dir=./; \
	    elif test -f $$tst; then dir=; \
	    else dir="$(srcdir)/"; fi; \
	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *" $$tst "*) \
		xpass=`expr $$xpass + 1`; \
		failed=`expr $$failed + 1`; \
		echo "XPASS: $$tst"; \
	      ;; \
	      *) \
		echo "PASS: $$tst"; \
	      ;; \
	      esac; \
	    elif test $$? -ne 77; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *" $$tst "*) \
		xfail=`expr $$xfail + 1`; \
		echo "XFAIL: $$tst"; \
	      ;; \
	      *) \
		failed=`expr $$failed + 1`; \
		echo "FAIL: $$tst"; \
	      ;; \
	      esac; \
	    else \
	      skip=`expr $$skip + 1`; \
	      echo "SKIP: $$tst"; \
	    fi; \
	  done; \
	  if test "$$failed" -eq 0; then \
	    if test "$$xfail" -eq 0; then \
	      banner="All $$all tests passed"; \
	    else \
	      banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
	    fi; \
	  else \
	    if test "$$xpass" -eq 0; then \
	      banner="$$failed of $$all tests failed"; \
	    else \
	      banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
	    fi; \
	  fi; \
	  dashes="$$banner"; \
	  skipped=""; \
	  if test "$$skip" -ne 0; then \
	    skipped="($$skip tests were not run)"; \
	    test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
	      dashes="$$skipped"; \
	  fi; \
	  report=""; \
	  if test "$$failed" -ne 0 && test -n "$(PACKAGE_BUGREPORT)"; then \
	    report="Please report to $(PACKAGE_BUGREPORT)"; \
	    test `echo "$$report" | wc -c` -le `echo "$$banner" | wc -c` || \
	      dashes="$$report"; \
	  fi; \
	  dashes=`echo "$$dashes" | sed s/./=/g`; \
	  echo "$$dashes"; \
	  echo "$$banner"; \
	  test -z "$$skipped" || echo "$$skipped"; \
	  test -z "$$report" || echo "$$report"; \
	  echo "$$dashes"; \
	  test "$$failed" -eq 0; \
	else :; fi

distdir: $(DISTFILES)
	$(am__remove_distdir)
	mkdir $(distdir)
	$(mkdir_p) $(distdir)/. $(distdir)/autotools $(distdir)/dbus $(distdir)/dbus/mainloop $(distdir)/examples $(distdir)/include $(distdir)/test
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkdir_p) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(SHELL) $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e '1{h;s/./=/g;p;x;}' -e '$${p;x;}'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
check: check-am
all-am: Makefile $(LTLIBRARIES) $(DATA) $(HEADERS) config.h
installdirs:
	for dir in "$(DESTDIR)$(pyexecdir)" "$(DESTDIR)$(pythondir)" "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(includedir)"; do \
	  test -z "$$dir" || $(mkdir_p) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool clean-pyexecLTLIBRARIES \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am: install-includeHEADERS install-nobase_pythonPYTHON \
	install-pkgconfigDATA

install-exec-am: install-pyexecLTLIBRARIES

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-includeHEADERS uninstall-info-am \
	uninstall-nobase_pythonPYTHON uninstall-pkgconfigDATA \
	uninstall-pyexecLTLIBRARIES

.PHONY: CTAGS GTAGS all all-am am--refresh check check-TESTS check-am \
	clean clean-generic clean-libtool clean-pyexecLTLIBRARIES \
	ctags dist dist-all dist-bzip2 dist-gzip dist-shar dist-tarZ \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-data install-data-am install-exec install-exec-am \
	install-includeHEADERS install-info install-info-am \
	install-man install-nobase_pythonPYTHON install-pkgconfigDATA \
	install-pyexecLTLIBRARIES install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-includeHEADERS \
	uninstall-info-am uninstall-nobase_pythonPYTHON \
	uninstall-pkgconfigDATA uninstall-pyexecLTLIBRARIES


cross-test-compile: all
cross-test-server:
	$(TESTS_ENVIRONMENT) $(PYTHON) test/cross-test-server.py
cross-test-client:
	$(TESTS_ENVIRONMENT) $(PYTHON) test/cross-test-client.py

# === Documentation ===

#all: api/index.html

#api api/index.html: $(nobase_python_PYTHON) _dbus_bindings.la _dbus_glib_bindings.la
#	rm -rf api
#	mkdir api
#	$(TESTS_ENVIRONMENT) $(EPYDOC) -o api --html \
#		--docformat restructuredtext -v \
#		`echo $(nobase_python_PYTHON) \
#			| sed -e 's#/__init__\.py##g' \
#				-e 's/\.py\>//g' -e 's#/#.#'g` \
#	|| { rm -rf api; exit 1; }

.PHONY: cross-test-compile cross-test-server cross-test-client
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
